### ISSUE TITLE
Problem with Valhalla Farm not collecting rewards

### ISSUE THREAD

**Issue by Changli666** [raws-97/pockie-ninja-farm-beta-1#1]
I try to farm Valhalla, but in rewards unable to claim, which means farm Valhalla does not work.

![untitled](https://github.com/user-attachments/assets/e2e65233-4b6c-4189-9525-c1ef5489d928)

**Comment by raws-97** [comment]
Okay. let me check on it.

**Comment by raws-97** [comment]
Hi @Changli666 Just fixed now. please try again. Thank you.
