### ISSUE TITLE
Error in Open Scrolls

### ISSUE THREAD

**Issue by IRhoAias** [raws-97/pockie-ninja-farm-beta-1#2]
EXCEPTION:  Locator.click: Error: strict mode violation: get_by_text("Use") resolved to 2 elements:
    1) <span>Imagine if we have to use seal breakers</span> aka get_by_text("Imagine if we have to use")
    2) <div class="context-menu__item">Use</div> aka get_by_text("Use", exact=True)

Call log:
waiting for get_by_text("Use")

 this happens in headless mode and normal mode as well

![image](https://github.com/user-attachments/assets/650dee8e-3b3d-4686-a839-5687445b422c)

**Comment by raws-97** [comment]
Fix on new commit. I'm using exact=True. to prevent this error.
