### ISSUE TITLE
Scrolls Loop

### ISSUE THREAD

**Issue by IRhoAias** [raws-97/pockie-ninja-farm-beta-1#3]
OPENED BROWSER
OPENED LINK
LOGGING INTO ACCOUNT...
LOGGED INTO ACCOUNT ItsRhoAias!
ENTERED SERVER!
CLOSING INTERFACE (CHAT, SETTINGS AND FRIENDS LIST)...
CLOSING CHAT...
CLOSING SETTINGS...
INTERFACES CLOSED!
You only have 1 S Rank Scroll left.
OPENED BROWSER
OPENED LINK
LOGGING INTO ACCOUNT...
LOGGED INTO ACCOUNT ItsRhoAias!
ENTERED SERVER!
CLOSING INTERFACE (CHAT, SETTINGS AND FRIENDS LIST)...
CLOSING CHAT...
CLOSING SETTINGS...
INTERFACES CLOSED!
You only have 1 S Rank Scroll left.
OPENED BROWSER
OPENED LINK
LOGGING INTO ACCOUNT...
LOGGED INTO ACCOUNT ItsRhoAias!
ENTERED SERVER!
CLOSING INTERFACE (CHAT, SETTINGS AND FRIENDS LIST)...
CLOSING CHAT...
CLOSING SETTINGS...
INTERFACES CLOSED!
You only have 1 S Rank Scroll left.
OPENED BROWSER
OPENED LINK
LOGGING INTO ACCOUNT...
LOGGED INTO ACCOUNT ItsRhoAias!
ENTERED SERVER!
CLOSING INTERFACE (CHAT, SETTINGS AND FRIENDS LIST)...
CLOSING CHAT...
CLOSING SETTINGS...
INTERFACES CLOSED!
You only have 1 S Rank Scroll left.
OPENED BROWSER
OPENED LINK
LOGGING INTO ACCOUNT...
LOGGED INTO ACCOUNT ItsRhoAias!
ENTERED SERVER!
CLOSING INTERFACE (CHAT, SETTINGS AND FRIENDS LIST)...
CLOSING CHAT...
CLOSING SETTINGS...
INTERFACES CLOSED!
You only have 1 S Rank Scroll left.
OPENED BROWSER
OPENED LINK
LOGGING INTO ACCOUNT...
LOGGED INTO ACCOUNT ItsRhoAias!
ENTERED SERVER!
CLOSING INTERFACE (CHAT, SETTINGS AND FRIENDS LIST)...
CLOSING CHAT...
CLOSING SETTINGS...
INTERFACES CLOSED!
You only have 1 S Rank Scroll left.
OPENED BROWSER
and repeats itself infinitely

It would be nice to have a window that pops up and when you accept it, the loop ends and you can put another scroll to farm.
like the old stop button that was in the original script about 5 months ago.

**Comment by raws-97** [comment]
Fixed on new commit. if scroll only 1 left. the page will close and you can start new session to open scroll.
