### ISSUE TITLE
Run.bat Missing Requirements

### ISSUE THREAD

**Issue by IRhoAias** [raws-97/pockie-ninja-farm-beta-1#7]
CALL pyinstaller -y -F main.py --add-data "venv/lib/site-packages/playwright/driver;playwright/driver" --add-data "venv/Lib/site-packages/sv_ttk;sv_ttk/" --add-data "venv/Lib/site-packages/sv_ttk/sv.tcl;."

**Comment by raws-97** [comment]
fixed
